In [18]:
import numpy as np

In [19]:
def project(A, b):
    x = np.dot(np.dot(np.linalg.inv(np.dot(A.T, A)), A.T), b)
    p = np.dot(A, x)
    e = b - p
    print('p:', p)
    print('e:', e)
    print('A.T times e:', np.dot(A.T, e))


In [11]:
A1 = np.array([[1,1],[0,1],[0,0]])
b1 = np.array([2,3,4]).T
project(A1, b1)

p: [ 2.  3.  0.]
e: [ 0.  0.  4.]
A.T times e: [ 0.  0.]


In [12]:
A2 = np.array([[1,1],[1,1],[0,1]])
b2 = np.array([4,4,6]).T
project(A2, b2)

p: [ 4.  4.  6.]
e: [ 0.  0.  0.]
A.T times e: [ 0.  0.]


In [5]:
A3 = np.array([[1,-6],[3,6],[4,8],[5,0],[7,8]])
c = np.array([1,0,0,0,0]).T
project(A3, c)

p: [  5.00000000e-01  -1.80000000e-01  -2.40000000e-01   4.00000000e-01
   1.11022302e-16]
e: [  5.00000000e-01   1.80000000e-01   2.40000000e-01  -4.00000000e-01
  -1.11022302e-16]
A.T times e: [ -1.33226763e-15  -1.77635684e-15]


In [33]:
A = np.array([[1, 2], [0, 3]])

In [34]:
eigval1, eigvec1 = np.linalg.eig(A)

In [42]:
eigvec1

array([[ 1.        ,  0.70710678],
       [ 0.        ,  0.70710678]])

In [36]:
eigval2, eigvec2 = np.linalg.eig(A.T)

In [37]:
eigvec2

array([[ 0.        ,  0.70710678],
       [ 1.        , -0.70710678]])

In [38]:
# eigvec1 = np.array([[1,0],[1,1]])
test = A - np.array([[1,0], [0,3]])


In [39]:
eigvec1, test

(array([[ 1.        ,  0.70710678],
        [ 0.        ,  0.70710678]]), array([[0, 2],
        [0, 0]]))

In [40]:
np.dot(eigvec1, test)

array([[ 0.,  2.],
       [ 0.,  0.]])